name: librelab_workspace
publish_to: none
environment:
  sdk: ^3.12.0

workspace:
  - librelab_api_contract
  - librelab_api_client
  - librelab_server
  - librelab_flutter
  - librelab_shared
  - packages/win32_registry_value_reader
  - packages/mdns_discovery/mdns_discovery
  - packages/mdns_discovery/mdns_discovery_bonsoir
  - packages/mdns_discovery/mdns_discovery_raw
  - packages/mdns_platform_check
  - packages/stepper_flow
  - packages/optional_field
  - packages/string_storage/string_storage
  - packages/string_storage/string_storage_shared_preferences

dev_dependencies:
  lints: ^6.1.0
  archive: ^4.0.9
  path: ^1.9.1
  yaml: ^3.1.3
