name: string_storage_shared_preferences
description: An implementation of string_storage that uses shared_preferences package
version: 0.0.1
publish_to: 'none'
resolution: workspace

environment:
  sdk: ^3.13.0-167.1.beta

dependencies:
  string_storage: ^0.0.1
  shared_preferences: ^2.5.5
