name: librelab_api_client
description: Dart client for consuming the LibreLab API
version: 0.0.1
publish_to: 'none'
resolution: workspace

environment:
  sdk: ^3.13.0-167.1.beta

dependencies:
  api_client:
    git:
      url: https://github.com/EchoEllet/dart-packages.git
      ref: c32c3eee45e7037641b32d609d4c5a29b0fa7e73
      path: packages/api_client
  clock: ^1.1.2
  librelab_api_contract: ^0.0.1
  logging: ^1.3.0
  meta: ^1.18.0

dev_dependencies:
  test: ^1.31.1
  checks: ^0.3.1
