name: string_storage
description: A low-level interface for reading and writing string values, abstracting the underlying persistence mechanism.
version: 0.0.1
publish_to: 'none'
resolution: workspace

environment:
  sdk: ^3.13.0-167.1.beta
