name: mdns_discovery
description: Abstracts the mDNS service discovery implementation
version: 1.0.0
publish_to: 'none'
resolution: workspace

environment:
  sdk: ^3.13.0-167.1.beta

dependencies:
  meta: ^1.17.0
