name: librelab_shared
description: Shared code between server and Flutter app
version: 1.0.0
publish_to: 'none'
resolution: workspace

environment:
  sdk: ^3.13.0-103.1.beta

dependencies:
  email_validator: ^3.0.0
  meta: ^1.17.0
  result:
    git:
      url: https://github.com/EchoEllet/dart-packages.git
      ref: c32c3eee45e7037641b32d609d4c5a29b0fa7e73
      path: packages/result

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
