name: mdns_discovery_bonsoir
description: Implementation of mdns_discovery that uses bonsoir Flutter plugin (platform-specific APIs)
version: 1.0.0
publish_to: 'none'
resolution: workspace

environment:
  sdk: ^3.11.5

dependencies:
  mdns_discovery: ^1.0.0
  bonsoir: ^7.0.0
  logging: ^1.3.0
