# Run "dart scripts/generate_pubspec_dart_code.dart" when updating any of these values.
name: librelab_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ^3.12.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  librelab_api_contract: ^0.0.1
  slang: ^4.14.0
  slang_flutter: ^4.14.0
  go_router: ^17.2.2
  lottie: ^3.3.3
  flutter_window_close: ^1.3.0
  bloc: ^9.2.0
  flutter_bloc: ^9.1.1
  meta: ^1.17.0
  freezed_annotation: ^3.1.0
  collection: ^1.19.1
  librelab_shared: ^1.0.0
  equatable: ^2.0.8
  logging: ^1.3.0
  mdns_discovery: ^1.0.0
  mdns_discovery_bonsoir: ^1.0.0
  mdns_discovery_raw: ^1.0.0
  url_launcher: ^6.3.2
  connectivity_plus_linux_portal: ^0.0.3
  mdns_platform_check: ^1.0.0
  stepper_flow: ^0.0.1
  api_client:
    git:
      url: https://github.com/EchoEllet/dart-packages.git
      ref: 570a0327c20ca5985e36c386ed6c63c59215e1bd
      path: packages/api_client
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  test: ^1.30.0
  build_runner: ^2.14.1
  flutter_gen_runner: ^5.14.1
  freezed: ^3.2.5
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  # To support "flutter gen-l10n" for the app package.
  generate: true

  assets:
    - assets/lottie/

flutter_gen:
  output: lib/generated/

  integrations:
    image: true
    lottie: true

flutter_launcher_icons:
  windows:
    generate: true
    image_path: assets/branding/icon.png
  macos:
    generate: true
    image_path: assets/branding/icon_framed.png
  # Linux: the launcher icon is handled using the packaging solutions (e.g., Flatpak)
  # or using a `.desktop` file.
