name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SECRET_databasePassword: 'XyEz-wvkhPlYQfrowm5lAv7L0yUufzxM'

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'

      - name: Start containers
        working-directory: librelab_server
        run: docker compose up --quiet-pull --quiet-build --build -d

      - name: Install dependencies
        working-directory: librelab_server
        run: dart pub get

      - name: Run tests
        working-directory: librelab_server
        run: dart test

      - name: Stop containers
        if: always()
        working-directory: librelab_server
        run: docker compose down -v
